apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-chart.fullname" . }}
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      port: 80
      name: web
  selector:
    {{- include "auth-chart.selectorLabels" . | nindent 4 }}
