apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  GREETING: Bonjour
  PG_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  PG_HOST: {{ include "postgresql.fullname" . | quote }}
  PG_PORT: {{ .Values.postgresql.service.port | quote }}
  PG_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
  PG_PASSWORD: {{ .Values.postgresql.postgresqlPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}

